export { Button } from "./Button";
export { Img } from "./Img";
export { Input } from "./Input";
export { RegInput } from "./RegInput";
export { p } from "./Paragraph";
export { LinkText } from "./LinkText";
export { Select } from "./Select";
export { Textarea } from "./Textarea";
export { BackgroundImage } from "./BackgroundImage";
export { Tabs, Tab, Content } from "./Tabs";
